# Generated by Django 3.1.7 on 2021-03-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateField(auto_created=True, auto_now_add=True, verbose_name='Created'),
        ),
    ]
