# Generated by Django 3.1.7 on 2021-03-19 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_auto_20210319_1752'),
        ('main', '0002_remove_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='custom_auth.profile'),
        ),
    ]
